import { Routes, Route } from 'react-router-dom'
import PaginaInicio from './pages/PaginaInicio'
import Blog from './pages/Blog'
import Contacto from './pages/Contacto'
import Galeria from './pages/Galeria'
import Navbar from './layout/Navbar'
import Footer from './layout/Footer'